model:
  - GCN
device:
  - cuda
batch_size:
  - 50
dense_dim:
  - 128

learning_rate:
  - 0.001
num_epochs:
  - 200
optimizer:
  - Adam
scheduler:
  -
    class: ExponentialLR
    args:
      gamma: 0.9
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - 0.25
l2:
  - 0.0
embedding_dim:
  - 32
num_layers:
  - 1
dropout:
  - 0.5
